[project]
name = "cryptography"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "ipykernel",
    "matplotlib",
    "sympy",
]

[tool.uv.workspace]
members = [
    "cryptography",
]
